### ISSUE TITLE
Compillation issues on AOloopControl_perfTest

### ISSUE THREAD

**Issue by a-sevin** [CACAO-org/CACAO#1]
Hi,
I have a problem during the compillation of cacao/src/AOloopControl_perfTest
gcc: error: .libs/AOloopControl_perfTest_DM.o: No such file or directory
gcc: error: .libs/AOloopControl_perfTest_status.o: No such file or directory

Same issue on thavis, I will search the bug this mornig.
Cheers,

Arnaud

**Comment by oguyon** [comment]
is the issue on dev or master branch ?
I will try to reproduce it

**Comment by a-sevin** [comment]
Master, sorry, I was very busy and I can't investigate it. I'm back on it

**Comment by oguyon** [comment]
please check dev first - master is lagging behind.
I may have fixed it in dev

**Comment by a-sevin** [comment]
My procedure:

```bash
git clone -b dev --recursive https://github.com/cacao-org/cacao cacao
cd cacao
autoreconf -vif
./configure CFLAGS='-Ofast -march=native' --enable-cuda --enable-magma
make
```
same error
```bash
gcc: error: .libs/AOloopControl_perfTest_DM.o: No such file or directory
gcc: error: .libs/AOloopControl_perfTest_status.o: No such file or directory
```
EDIT: same error with "./configure"

**Comment by oguyon** [comment]
OK - I will look into it in ~14hr when my meeting ends

**Comment by a-sevin** [comment]
Solved when you update submodules to follow their dev branch:

```bash
git submodule foreach git checkout dev
```

Modifications push in c78f94635cbda823be0c880877000d501b281212

**Comment by oguyon** [comment]
thks - will merge dev to master in all submodules to fix issue

**Comment by oguyon** [comment]
master has been synced to dev
added travis badges (dev and master build status) to README.md
