### ISSUE TITLE
cacao should install setuid

### ISSUE THREAD

**Issue by joseph-long** [CACAO-org/CACAO#11]
It looks like this line:

https://github.com/cacao-org/cacao/blob/722308cedbd46df689f75696f20e52b8126bf7a3/CMakeLists.txt#L341

Should be changed to look like:

`install(TARGETS cacao DESTINATION bin PERMISSIONS SETUID)`

I'd PR directly but it's such a small change I don't want to mess with cherry-picking... https://github.com/magao-x/cacao/commit/1ca5b01d4e86caa17b3ab25ef5fb654bf3a4d9e8

**Comment by oguyon** [comment]
Change made in dev branch.
Full change:

    set(PROGRAM_PERMISSIONS_DEFAULT

    OWNER_WRITE OWNER_READ OWNER_EXECUTE
    GROUP_READ GROUP_EXECUTE
    WORLD_READ WORLD_EXECUTE)
    install(TARGETS cacao DESTINATION bin PERMISSIONS ${PROGRAM_PERMISSIONS_DEFAULT} SETUID)


Note: may need to write "/usr/local/magma/lib" to /etc/ld.so.conf.d/magma.conf
`

**Comment by joseph-long** [comment]
Thanks @oguyon ! Will pull into our downstream fork
