### ISSUE TITLE
readme install instructions inconsistent

### ISSUE THREAD

**Issue by jaredmales** [CACAO-org/CACAO#12]
https://github.com/cacao-org/cacao/blob/4e89f3170abd092f5f16abe08fcc3226c8fcd619/README.md?plain=1#L59

I think that line should point at https://github.com/milk-org/milk instead of milk-package, or the following code block should be updated to use milk-package.

**Comment by oguyon** [comment]
Yes indeed - Thanks !
I just updated the link on the README page.
