### ISSUE TITLE
Set loop number of mfilt streams correctly

### ISSUE THREAD

**Issue by jbOhland93** [CACAO-org/CACAO#19]
- Set up scexao-vispyr-bin2 example
- The loop number is 7
- The arrays for the modal processing are numbered with 0, i.e.
      - ``aol0_mmultfact`` instead of ``aol7_mmultfact``
      - ``aol0_mlimitfact`` instead of ``aol7_mlimitfact``
      - ``aol0_mgainfact`` instead of ``aol7_mgainfact``

**Comment by DasVinch** [comment]
Yes, spotted recently as well.

FPS parameter `mfilt-LOOPNUMBER.AOloopindex` defaults to 0 and should automatically be set to LOOPNUMBER instead.

**Comment by DasVinch** [comment]
Fixed in 0a02635e.
Feel like a need for redundant info... but at least this covers.
