### ISSUE TITLE
stray paste in docs?

### ISSUE THREAD

**Issue by jaredmales** [CACAO-org/CACAO#27]
https://github.com/cacao-org/cacao/blob/ace318b0457face4b5c701e4767c873ff0f6e074/AOloopControl/examples/scexao-vispyr-bin2-conf/README.md?plain=1#L239

This and line below it look like maybe a stray paste to me?

**Comment by jaredmales** [comment]
https://github.com/cacao-org/cacao/pull/30

**Comment by DasVinch** [comment]
Stray draft notes indeed.

There's an ultra-primitive pycacao python package in cacao that you may have noticed...

My idea there was to transition non-RT linear algebra to python for more versatility and readability. That line you highlighted for instance allows to generate a poking basis made of spatially randomized Hadamard modes, which removes a few artifacts from the default hadamard poking.
