### ISSUE TITLE
cacao 'make' fails at AOloopControl_computeCalib_loDMmodes.c

### ISSUE THREAD

**Issue by thaynecurrie** [CACAO-org/CACAO#4]
1. AOloopControl_computeCalib_loDMmodes.c:68:2: error: expected identifier or '(' before '/' token
 */

fixed by 
..reversing the order of * and / in lines 67 and 78: i.e. /*     */ 

2. AOloopControl_computeCalib_loDMmodes.c:92:2: error: expected identifier or '(' before '/' token
 */

True fix unknown, but error no longer triggered by either reversing the order of * and / (i.e. /*) or completely removing this line.

3. declaration errors from line 111 onwards cause 'make' fail.  Solution: not known right now.

(Error log)

AOloopControl_computeCalib_loDMmodes.c:111:8: error: unknown type name 'DATA'
 extern DATA data;
        ^
AOloopControl_computeCalib_loDMmodes.c: In function 'AOloopControl_computeCalib_mkloDMmodes':
AOloopControl_computeCalib_loDMmodes.c:168:5: warning: implicit declaration of function 'list_image_ID' [-Wimplicit-function-declaration]
     list_image_ID();
     ^
AOloopControl_computeCalib_loDMmodes.c:169:14: warning: implicit declaration of function 'image_ID' [-Wimplicit-function-declaration]
     IDmask = image_ID("dmmask");
              ^
AOloopControl_computeCalib_loDMmodes.c:178:18: warning: implicit declaration of function 'create_2Dimage_ID' [-Wimplicit-function-declaration]
         IDmask = create_2Dimage_ID("dmmask", msizex, msizey);
                  ^
AOloopControl_computeCalib_loDMmodes.c:188:21: error: request for member 'image' in something not a structure or union
                 data.image[IDmask].array.F[jj*msizex+ii] = val0*val1;
                     ^
AOloopControl_computeCalib_loDMmodes.c:190:9: warning: implicit declaration of function 'save_fits' [-Wimplicit-function-declaration]
         save_fits("dmmask", "!dmmask.fits");
         ^
AOloopControl_computeCalib_loDMmodes.c:202:35: error: request for member 'image' in something not a structure or union
                 xc1 += 1.0*ii*data.image[IDmask].array.F[jj*msizex+ii];
                                   ^
AOloopControl_computeCalib_loDMmodes.c:203:35: error: request for member 'image' in something not a structure or union
                 yc1 += 1.0*jj*data.image[IDmask].array.F[jj*msizex+ii];
                                   ^
AOloopControl_computeCalib_loDMmodes.c:204:29: error: request for member 'image' in something not a structure or union
                 totm += data.image[IDmask].array.F[jj*msizex+ii];
                             ^
AOloopControl_computeCalib_loDMmodes.c:214:12: warning: implicit declaration of function 'arith_image_total' [-Wimplicit-function-declaration]
     totm = arith_image_total("dmmask");
            ^
AOloopControl_computeCalib_loDMmodes.c:215:23: error: request for member 'image' in something not a structure or union
     if((msizex != data.image[IDmask].md[0].size[0])||(msizey != data.image[IDmask].md[0].size[1]))
                       ^
AOloopControl_computeCalib_loDMmodes.c:215:69: error: request for member 'image' in something not a structure or union
     if((msizex != data.image[IDmask].md[0].size[0])||(msizey != data.image[IDmask].md[0].size[1]))
                                                                     ^
AOloopControl_computeCalib_loDMmodes.c:217:105: error: request for member 'image' in something not a structure or union
         printf("ERROR: file dmmask size (%ld %ld) does not match expected size (%ld %ld)\n", (long) data.image[IDmask].md[0].size[0], (long) data.image[IDmask].md[0].size[1], (long) msizex, (long) msizey);
                                                                                                         ^
AOloopControl_computeCalib_loDMmodes.c:217:146: error: request for member 'image' in something not a structure or union
         printf("ERROR: file dmmask size (%ld %ld) does not match expected size (%ld %ld)\n", (long) data.image[IDmask].md[0].size[0], (long) data.image[IDmask].md[0].size[1], (long) msizex, (long) msizey);
                                                                                                                                                  ^
AOloopControl_computeCalib_loDMmodes.c:232:5: warning: implicit declaration of function 'linopt_imtools_makeCPAmodes' [-Wimplicit-function-declaration]
     linopt_imtools_makeCPAmodes("CPAmodes", msizex, CPAmax, deltaCPA, 0.5*msizex, 1.2, 0);
     ^
AOloopControl_computeCalib_loDMmodes.c:238:58: error: request for member 'image' in something not a structure or union
     printf("  %ld %ld %ld\n", msizex, msizey, (long) data.image[ID0].md[0].size[2]-1 );
                                                          ^
AOloopControl_computeCalib_loDMmodes.c:239:10: warning: implicit declaration of function 'create_3Dimage_ID' [-Wimplicit-function-declaration]
     ID = create_3Dimage_ID(ID_name, msizex, msizey, data.image[ID0].md[0].size[2]-1+NBZ);
          ^
AOloopControl_computeCalib_loDMmodes.c:239:57: error: request for member 'image' in something not a structure or union
     ID = create_3Dimage_ID(ID_name, msizex, msizey, data.image[ID0].md[0].size[2]-1+NBZ);
                                                         ^
AOloopControl_computeCalib_loDMmodes.c:245:53: error: request for member 'image' in something not a structure or union
     IDmfcpa = create_2Dimage_ID("modesfreqcpa", data.image[ID0].md[0].size[2]-1+NBZ, 1);
                                                     ^
AOloopControl_computeCalib_loDMmodes.c:252:13: error: request for member 'image' in something not a structure or union
         data.image[IDmfcpa].array.F[k] = zcpa[k];
             ^
AOloopControl_computeCalib_loDMmodes.c:260:21: error: request for member 'image' in something not a structure or union
                 data.image[ID].array.F[k*msizex*msizey+jj*msizex+ii] = Zernike_value(zindex[k], r, PA);
                     ^
AOloopControl_computeCalib_loDMmodes.c:267:20: error: request for member 'image' in something not a structure or union
     for(k=0; k<data.image[ID0].md[0].size[2]-1; k++)
                    ^
AOloopControl_computeCalib_loDMmodes.c:269:13: error: request for member 'image' in something not a structure or union
         data.image[IDmfcpa].array.F[k+NBZ] = data.image[IDfreq].array.F[k+1];
             ^
AOloopControl_computeCalib_loDMmodes.c:269:50: error: request for member 'image' in something not a structure or union
         data.image[IDmfcpa].array.F[k+NBZ] = data.image[IDfreq].array.F[k+1];
                                                  ^
AOloopControl_computeCalib_loDMmodes.c:271:17: error: request for member 'image' in something not a structure or union
             data.image[ID].array.F[(k+NBZ)*msizex*msizey+ii] = data.image[ID0].array.F[(k+1)*msizex*msizey+ii];
                 ^
AOloopControl_computeCalib_loDMmodes.c:271:68: error: request for member 'image' in something not a structure or union
             data.image[ID].array.F[(k+NBZ)*msizex*msizey+ii] = data.image[ID0].array.F[(k+1)*msizex*msizey+ii];
                                                                    ^
AOloopControl_computeCalib_loDMmodes.c:275:20: error: request for member 'image' in something not a structure or union
     for(k=0; k<data.image[ID0].md[0].size[2]-1+NBZ; k++)
                    ^
AOloopControl_computeCalib_loDMmodes.c:284:21: error: request for member 'image' in something not a structure or union
                 data.image[IDtm].array.F[ii] = data.image[ID].array.F[k*msizex*msizey+ii];
                     ^
AOloopControl_computeCalib_loDMmodes.c:284:52: error: request for member 'image' in something not a structure or union
                 data.image[IDtm].array.F[ii] = data.image[ID].array.F[k*msizex*msizey+ii];
                                                    ^
AOloopControl_computeCalib_loDMmodes.c:285:13: warning: implicit declaration of function 'linopt_imtools_image_fitModes' [-Wimplicit-function-declaration]
             linopt_imtools_image_fitModes("tmpmode", "emodes", "dmmask", 1.0e-2, "lcoeff", 0);
             ^
AOloopControl_computeCalib_loDMmodes.c:286:13: warning: implicit declaration of function 'linopt_imtools_image_construct' [-Wimplicit-function-declaration]
             linopt_imtools_image_construct("emodes", "lcoeff", "em00");
             ^
AOloopControl_computeCalib_loDMmodes.c:287:13: warning: implicit declaration of function 'delete_image_ID' [-Wimplicit-function-declaration]
             delete_image_ID("lcoeff");
             ^
AOloopControl_computeCalib_loDMmodes.c:294:21: error: request for member 'image' in something not a structure or union
                 data.image[ID].array.F[k*msizex*msizey+ii] = data.image[IDtm].array.F[ii] - coeff*data.image[IDem].array.F[ii];
                     ^
AOloopControl_computeCalib_loDMmodes.c:294:66: error: request for member 'image' in something not a structure or union
                 data.image[ID].array.F[k*msizex*msizey+ii] = data.image[IDtm].array.F[ii] - coeff*data.image[IDem].array.F[ii];
                                                                  ^
AOloopControl_computeCalib_loDMmodes.c:294:103: error: request for member 'image' in something not a structure or union
                 data.image[ID].array.F[k*msizex*msizey+ii] = data.image[IDtm].array.F[ii] - coeff*data.image[IDem].array.F[ii];
                                                                                                       ^
AOloopControl_computeCalib_loDMmodes.c:305:26: error: request for member 'image' in something not a structure or union
             totvm += data.image[ID].array.F[k*msizex*msizey+ii]*data.image[IDmask].array.F[ii];
                          ^
AOloopControl_computeCalib_loDMmodes.c:305:69: error: request for member 'image' in something not a structure or union
             totvm += data.image[ID].array.F[k*msizex*msizey+ii]*data.image[IDmask].array.F[ii];
                                                                     ^
AOloopControl_computeCalib_loDMmodes.c:311:17: error: request for member 'image' in something not a structure or union
             data.image[ID].array.F[k*msizex*msizey+ii] -= offset;
                 ^
AOloopControl_computeCalib_loDMmodes.c:312:17: error: request for member 'image' in something not a structure or union
             data.image[ID].array.F[k*msizex*msizey+ii] *= data.image[IDmask].array.F[ii];
                 ^
AOloopControl_computeCalib_loDMmodes.c:312:63: error: request for member 'image' in something not a structure or union
             data.image[ID].array.F[k*msizex*msizey+ii] *= data.image[IDmask].array.F[ii];
                                                               ^
AOloopControl_computeCalib_loDMmodes.c:317:27: error: request for member 'image' in something not a structure or union
             offset += data.image[ID].array.F[k*msizex*msizey+ii];
                           ^
AOloopControl_computeCalib_loDMmodes.c:322:17: error: request for member 'image' in something not a structure or union
             data.image[ID].array.F[k*msizex*msizey+ii] -= offset/msizex/msizey;
                 ^
AOloopControl_computeCalib_loDMmodes.c:323:24: error: request for member 'image' in something not a structure or union
             rms += data.image[ID].array.F[k*msizex*msizey+ii]*data.image[ID].array.F[k*msizex*msizey+ii];
                        ^
AOloopControl_computeCalib_loDMmodes.c:323:67: error: request for member 'image' in something not a structure or union
             rms += data.image[ID].array.F[k*msizex*msizey+ii]*data.image[ID].array.F[k*msizex*msizey+ii];
                                                                   ^
AOloopControl_computeCalib_loDMmodes.c:328:17: error: request for member 'image' in something not a structure or union
             data.image[ID].array.F[k*msizex*msizey+ii] /= rms;
                 ^
AOloopControl_computeCalib_loDMmodes.c:332:20: error: request for member 'image' in something not a structure or union
     for(k=0; k<data.image[ID0].md[0].size[2]-1+NBZ; k++)
                    ^
AOloopControl_computeCalib_loDMmodes.c:337:17: error: request for member 'image' in something not a structure or union
             data.image[ID].array.F[k*msizex*msizey+ii] -= offset/msizex/msizey;
                 ^
AOloopControl_computeCalib_loDMmodes.c:338:24: error: request for member 'image' in something not a structure or union
             rms += data.image[ID].array.F[k*msizex*msizey+ii]*data.image[ID].array.F[k*msizex*msizey+ii];
                        ^
AOloopControl_computeCalib_loDMmodes.c:338:67: error: request for member 'image' in something not a structure or union
             rms += data.image[ID].array.F[k*msizex*msizey+ii]*data.image[ID].array.F[k*msizex*msizey+ii];
                                                                   ^
AOloopControl_computeCalib_loDMmodes.c:361:28: error: request for member 'image' in something not a structure or union
             for(k=0; k<data.image[ID].md[0].size[2]; k++)
                            ^
AOloopControl_computeCalib_loDMmodes.c:364:28: error: request for member 'image' in something not a structure or union
                     if(data.image[IDmask].array.F[ii]<0.98)
                            ^
AOloopControl_computeCalib_loDMmodes.c:365:29: error: request for member 'image' in something not a structure or union
                         data.image[ID].array.F[k*msizex*msizey+ii] = data.image[IDg].array.F[k*msizex*msizey+ii];
                             ^
AOloopControl_computeCalib_loDMmodes.c:365:74: error: request for member 'image' in something not a structure or union
                         data.image[ID].array.F[k*msizex*msizey+ii] = data.image[IDg].array.F[k*msizex*msizey+ii];
                                                                          ^
AOloopControl_computeCalib_loDMmodes.c:382:24: error: request for member 'image' in something not a structure or union
         for(m=0; m<data.image[ID].md[0].size[2]; m++)
                        ^
AOloopControl_computeCalib_loDMmodes.c:387:21: error: request for member 'image' in something not a structure or union
                 data.image[IDtmp].array.F[ii] = data.image[ID].array.F[m*msizex*msizey+ii];
                     ^
AOloopControl_computeCalib_loDMmodes.c:387:53: error: request for member 'image' in something not a structure or union
                 data.image[IDtmp].array.F[ii] = data.image[ID].array.F[m*msizex*msizey+ii];
                                                     ^
AOloopControl_computeCalib_loDMmodes.c:388:21: error: request for member 'image' in something not a structure or union
                 data.image[IDtmp1].array.F[ii] = data.image[IDmask].array.F[ii] * (1.0-data.image[IDslaved].array.F[ii]);
                     ^
AOloopControl_computeCalib_loDMmodes.c:388:54: error: request for member 'image' in something not a structure or union
                 data.image[IDtmp1].array.F[ii] = data.image[IDmask].array.F[ii] * (1.0-data.image[IDslaved].array.F[ii]);
                                                      ^
AOloopControl_computeCalib_loDMmodes.c:388:92: error: request for member 'image' in something not a structure or union
                 data.image[IDtmp1].array.F[ii] = data.image[IDmask].array.F[ii] * (1.0-data.image[IDslaved].array.F[ii]);
                                                                                            ^
AOloopControl_computeCalib_loDMmodes.c:389:21: error: request for member 'image' in something not a structure or union
                 data.image[IDtmp2].array.F[ii] = data.image[IDtmp1].array.F[ii];
                     ^
AOloopControl_computeCalib_loDMmodes.c:389:54: error: request for member 'image' in something not a structure or union
                 data.image[IDtmp2].array.F[ii] = data.image[IDtmp1].array.F[ii];
                                                      ^
AOloopControl_computeCalib_loDMmodes.c:402:33: error: request for member 'image' in something not a structure or union
                         if((data.image[IDtmp1].array.F[jj*msizex+ii]<0.5) && (data.image[IDslaved].array.F[jj*msizex+ii]>0.5))
                                 ^
AOloopControl_computeCalib_loDMmodes.c:402:83: error: request for member 'image' in something not a structure or union
                         if((data.image[IDtmp1].array.F[jj*msizex+ii]<0.5) && (data.image[IDslaved].array.F[jj*msizex+ii]>0.5))
                                                                                   ^
AOloopControl_computeCalib_loDMmodes.c:405:39: error: request for member 'image' in something not a structure or union
                             vxp = data.image[IDtmp].array.F[jj*msizex+(ii+1)];
                                       ^
AOloopControl_computeCalib_loDMmodes.c:406:39: error: request for member 'image' in something not a structure or union
                             cxp = data.image[IDtmp1].array.F[jj*msizex+(ii+1)];
                                       ^
AOloopControl_computeCalib_loDMmodes.c:408:39: error: request for member 'image' in something not a structure or union
                             vxm = data.image[IDtmp].array.F[jj*msizex+(ii-1)];
                                       ^
AOloopControl_computeCalib_loDMmodes.c:409:39: error: request for member 'image' in something not a structure or union
                             cxm = data.image[IDtmp1].array.F[jj*msizex+(ii-1)];
                                       ^
AOloopControl_computeCalib_loDMmodes.c:411:39: error: request for member 'image' in something not a structure or union
                             vyp = data.image[IDtmp].array.F[(jj+1)*msizex+ii];
                                       ^
AOloopControl_computeCalib_loDMmodes.c:412:39: error: request for member 'image' in something not a structure or union
                             cyp = data.image[IDtmp1].array.F[(jj+1)*msizex+ii];
                                       ^
AOloopControl_computeCalib_loDMmodes.c:414:39: error: request for member 'image' in something not a structure or union
                             vym = data.image[IDtmp].array.F[(jj-1)*msizex+ii];
                                       ^
AOloopControl_computeCalib_loDMmodes.c:415:39: error: request for member 'image' in something not a structure or union
                             cym = data.image[IDtmp1].array.F[(jj-1)*msizex+ii];
                                       ^
AOloopControl_computeCalib_loDMmodes.c:421:37: error: request for member 'image' in something not a structure or union
                                 data.image[IDtmp].array.F[jj*msizex+ii] = (vxp*cxp+vxm*cxm+vyp*cyp+vym*cym)/ctot;
                                     ^
AOloopControl_computeCalib_loDMmodes.c:422:37: error: request for member 'image' in something not a structure or union
                                 data.image[IDtmp2].array.F[jj*msizex+ii] = 1.0;
                                     ^
AOloopControl_computeCalib_loDMmodes.c:427:25: error: request for member 'image' in something not a structure or union
                     data.image[IDtmp1].array.F[ii] = data.image[IDtmp2].array.F[ii];
                         ^
AOloopControl_computeCalib_loDMmodes.c:427:58: error: request for member 'image' in something not a structure or union
                     data.image[IDtmp1].array.F[ii] = data.image[IDtmp2].array.F[ii];
                                                          ^
AOloopControl_computeCalib_loDMmodes.c:430:21: error: request for member 'image' in something not a structure or union
                 data.image[ID].array.F[m*msizex*msizey+ii] = data.image[IDtmp].array.F[ii];
                     ^
AOloopControl_computeCalib_loDMmodes.c:430:66: error: request for member 'image' in something not a structure or union
                 data.image[ID].array.F[m*msizex*msizey+ii] = data.image[IDtmp].array.F[ii];
                                                                  ^
make[3]: *** [AOloopControl_computeCalib_loDMmodes.lo] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

**Comment by oguyon** [comment]
This is due to bad comments brackets.
Confirmed that clean install from dev branch does not exhibit this issue
