### ISSUE TITLE
Cannot set astrogrid to bin=1

### ISSUE THREAD

**Issue by mileslucas** [CACAO-org/CACAO#46]
https://github.com/cacao-org/cacao/blob/3cc0b7ea956bacf487e2707b4bee1bfa85ddb5b6/AOloopControl_DM/scripts/cacao-astrogrid-mkgrid#L32

This is the cause of the issue, needs to be 
```suggestion
 MSopt+=( "b1:binfact2:setbin1::use bin factor 1" ) 
```

**Comment by DasVinch** [comment]
Fixed at 42187b89. Thanks for figuring it out.
