### ISSUE TITLE
GPU-compatible data format

### ISSUE THREAD

**Issue by oguyon** [CACAO-org/CACAO#5]
Data format should support GPU-hosted memory locations. Need to address synchronization issues. NVIDIA's managed memory is a model, but it suffers from sub-optimal performance because it forces synchronization between GPU and CPU memory even when not needed.

**Comment by a-sevin** [comment]
Maybe, it could be an issue in the ImageStreamIO repo ?

**Comment by oguyon** [comment]
Yes - closing here and re-opening in ImageStreamIO
