### ISSUE TITLE
Revisit how processes are managed

### ISSUE THREAD

**Issue by oguyon** [CACAO-org/CACAO#6]
The current "processes run in tmux sessions" may not be adequate... some have quoted "bound to fail" to describe it. 
Need exploring better framework - some tools already identified, more exploration / sandboxing needed

**Comment by a-sevin** [comment]
The quote is from the page 208 of this [book](https://github.com/TechBookHunter/Free-Python-Books/blob/master/book/Expert%20Python%20Programming%20-%20Second%20Edition.pdf).
The author proposes 2 solutions:

- [Supervisor](http://supervisord.org/)
- [Circus](https://circus.readthedocs.io/en/latest/)

For pure monitoring, I also find [monit](https://mmonit.com/monit/) which seems to be more active...

**Comment by oguyon** [comment]
The book gives a clear list of what we'll want the process manager to do:
[1] restart process if it quits
[2] track its state
[3] capture stdout/stderr
[4] permissions
[5] set environment variables

Maybe we can do this on top of the existing tmux scheme. The tmux scheme is convenient for debugging and detailed inspection: logging into a terminal has its advantages.
Requirements [3], [4] and [5] can be done by adding a lightweight layer of standard system-available tools. Requirement [2] can be done by monitoring PID load + having a shared memory counter/heartbeat in the process (so that we can track loop frequency as seen by the process, dropped frames, time to complete each loop iteration, etc...).

Restarting processes if they quit is probably not something we would want to do automatically... if it quits, best to figure out why and address the issue.

I suspect we'll want to combine the process manager with the hardware setup: which cores / memory banks should be shielded, setting up cpu sets, priorities. This is super important for low-latency operation.

Does all of this mean we're better off setting up our own process management framework from scratch  ?

**Comment by oguyon** [comment]
we now have a process manager that tracks status, can pause, step and stop loops, and scans the /proc filesystem to identify where processes reside and what is their use of resources.
The process manager also includes a human-readable messaging.

See file processtools.c in module CommandLineInterface for details

C/ncurses based GUI is already provided. Python GUI under development
